FROM nginx:1.19

LABEL maintainer="Skrjs<375259904@qq.com>" \ 
    org.label-schema.name="web" \
    org.label-schema.vendor="skrjs" \
    org.label-schema.schema-version="1.0"

EXPOSE 80

COPY ./config/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /etc/nginx/html

CMD ["nginx", "-g", "daemon off;"]
